{
  "hash": "bb8af54b643750491a220a09766e4007",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction & Visualization\"\nformat: html\neditor: visual\n---\n\n\n\n## Aim\n\nWe want to simulate COVID 19 spread through Salt Lake County. We work with 3 datasets overall.\n\nFirst, from US Census Bureau, we decode how many agents go in each age from in the simulation. We also make use of another dataset, that gives us an idea about contacts each age group has with every other age group. ( who interacts with whom ). Model uses these 2 datasets to simulate what could happen with one infected person. We run it 500 times to capture uncerrainity\n\nAt last, we compare results with the dataset - \"utah_covid_data\" from epiworldRcalibrate, which shows actual out break - the daily cases (new) and trends, to verify accuracy of our model.\n\n## Real Outbreak Visualization\n\nLets visualize actual trends in cases during covid 19 using utah_covid_data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"utah_covid_data\")\nlast_date  <- max(utah_covid_data$Date, na.rm = TRUE)\ncovid_data <- utah_covid_data |>\n  filter(Date > (last_date - 61)) |>\n  arrange(Date)\ncovid_data <- covid_data |>\n  mutate(roll7 = zoo::rollmean(Daily.Cases, k = 7, fill = NA, align = \"right\"))\n\ncat(\n  \"\\nCOVID DATA\\n\",\n  \"Rows:\", nrow(covid_data), \"\\n\",\n  \"Date range:\", as.character(min(covid_data$Date)), \"to\", as.character(max(covid_data$Date)), \"\\n\",\n  \"Total cases:\", sum(covid_data$Daily.Cases), \"\\n\",\n  \"Mean daily cases:\", round(mean(covid_data$Daily.Cases), 1), \"\\n\",\n  \"Median daily cases:\", round(median(covid_data$Daily.Cases), 1), \"\\n\",\n  \"Max daily cases:\", max(covid_data$Daily.Cases), \"\\n\",\n  \"Unique status values:\", paste(unique(covid_data$Status), collapse = \", \"), \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCOVID DATA\n Rows: 61 \n Date range: 2025-03-07 to 2025-05-06 \n Total cases: 2034 \n Mean daily cases: 33.3 \n Median daily cases: 31 \n Max daily cases: 107 \n Unique status values: Incidence Plateau \n```\n\n\n:::\n:::\n\n\nAs shown, we just have data about the covid 19 cases for about 2 months from March 2025 to May 2025, mean and median new cases per day being 33 and 31 respectively. On May 19 2025, the number of new cases topped abruptly to 107, suggesting possibility of an event occuring, or probably a delayed reporting after a weekend.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(covid_data, aes(x = Date, y = Daily.Cases)) +\n  geom_col(fill = \"#2166ac\", alpha = 0.8) +\n  geom_smooth(method = \"loess\", span = 0.35, se = FALSE, colour = \"#d6604d\") +\n  scale_y_continuous(labels = scales::comma) + \n  labs(title = \"Daily COVID-19 Cases — Utah\",\n       x = NULL, y = \"Daily cases\") +   theme_minimal()\nprint(p1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np5 <- covid_data |>\n  mutate(\n    # recompute all averages from Daily.Cases directly\n    ma3        = zoo::rollmean(Daily.Cases, k = 3, fill = NA, align = \"right\"),\n    ma3_smooth = zoo::rollmean(ma3,         k = 3, fill = NA, align = \"right\"),\n    roll7      = zoo::rollmean(Daily.Cases, k = 7, fill = NA, align = \"right\")\n  ) |>\n  tidyr::pivot_longer(\n    cols      = c(Daily.Cases, ma3, ma3_smooth, roll7),\n    names_to  = \"Metric\",\n    values_to = \"Value\"\n  ) |>\n  mutate(Metric = dplyr::recode(Metric,\n                                \"Daily.Cases\" = \"Raw\",\n                                \"ma3\"         = \"3-Day MA\",\n                                \"ma3_smooth\"  = \"Smoothed 3-Day MA\",\n                                \"roll7\"       = \"7-Day MA\"\n  )) |>\n  ggplot(aes(x = Date, y = Value, colour = Metric)) +\n  geom_line(linewidth = 0.9, alpha = 0.85, na.rm = TRUE) +\n  scale_colour_manual(\n    values = c(\n      \"Raw\"              = \"#2166ac\",\n      \"3-Day MA\"         = \"#d73027\",\n      \"Smoothed 3-Day MA\"= \"#4dac26\",\n      \"7-Day MA\"         = \"#f4a582\"\n    )\n  ) +\n  labs(\n    title = \"Raw Cases vs Moving Averages\",\n    x     = NULL,\n    y     = \"Cases\",\n    colour = NULL\n  ) +\n  theme_minimal()\n\nprint(p5)\n```\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nAs Shown above, a 7 day raw scores were a little too noisy, so I also plotted a 3-Day avg plot and a 7 - Day Avg plot as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndnames <- c(\n  \"0-4\",\"5-9\",\"10-14\",\"15-19\",\"20-24\",\"25-29\",\"30-34\",\n  \"35-39\",\"40-44\",\"45-49\",\"50-54\",\"55-59\",\"60-64\",\n  \"65-69\",\"70-74\",\"75-79\",\"80+\"\n)\n\nmm_url <- paste0(\n  \"https://raw.githubusercontent.com/epistorm/Epistorm-Mix/\",\n  \"05966ba49c7b49fb1cd902d6b98b3be0bb2785a8/matrices/M_matrix/\",\n  \"Total-M-by5_80-matrix.csv\"\n)\nmm_file <- file.path(tempdir(), \"contact_matrix.csv\")\ndownload.file(mm_url, destfile = mm_file, quiet = TRUE)\n\nmm_raw <- fread(mm_file)\nif (\"resp_age_by5_80\" %in% names(mm_raw)) {\n  mm_raw[, resp_age_by5_80 := NULL]\n}\nmm <- as.matrix(mm_raw)\ndimnames(mm) <- list(dnames, dnames)\n\n# row stochastic version\nmm_stochastic <- mm / rowSums(mm)\n\ncat(\n  \"\\n===== MIXING MATRIX =====\\n\",\n  \"Dimensions:\", nrow(mm), \"x\", ncol(mm), \"\\n\",\n  \"Age group with most contacts:\", dnames[which.max(rowSums(mm))], \"\\n\",\n  \"Age group with least contacts:\", dnames[which.min(rowSums(mm))], \"\\n\",\n  \"Row-stochastic valid (rows sum to 1):\", all(abs(rowSums(mm_stochastic) - 1) < 1e-9), \"\\n\",\n  \"Row sums:\\n\", paste(names(round(rowSums(mm), 2)), round(rowSums(mm), 2), collapse = \"\\n \"), \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n===== MIXING MATRIX =====\n Dimensions: 17 x 17 \n Age group with most contacts: 15-19 \n Age group with least contacts: 80+ \n Row-stochastic valid (rows sum to 1): TRUE \n Row sums:\n 0-4 6.91\n 5-9 10.09\n 10-14 8.69\n 15-19 10.31\n 20-24 7.74\n 25-29 6.03\n 30-34 8.22\n 35-39 8.14\n 40-44 7.71\n 45-49 7.81\n 50-54 7.44\n 55-59 8.93\n 60-64 5.24\n 65-69 5.25\n 70-74 4.49\n 75-79 5.08\n 80+ 3.75 \n```\n\n\n:::\n:::\n\n\nThe above results show patterns for contacts. The group 15-19 interacts the most, whereas 80+ interacts the least.\n\nIt seems legit, cause middle aged adults usually are confined to their workspaces and dont make much contact with each other. Its a little surprising to see people of age 55-59 have a contact rate of 8.93%, higher than middle aged adults.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np8 <- as.data.frame(as.table(mm)) |>\n  rename(contactor = Var1, contactee = Var2, contacts = Freq) |>\n  mutate(\n    contactor = factor(contactor, levels = dnames),\n    contactee = factor(contactee, levels = rev(dnames))\n  ) |>\n  ggplot(aes(x = contactor, y = contactee, fill = contacts)) +\n  geom_tile(colour = \"white\", linewidth = 0.3) +\n  scale_fill_gradient(low = \"#f7fbff\", high = \"#08306b\", name = \"Contacts/day\") +\n  labs(title = \"Age-Structured Contact Matrix\",\n       x = \"Contactor\", y = \"Contactee\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\nprint(p8)\n```\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nContact matrix shows contacts made by one group with the other.\n\nMostly, the trend shows every group makes most contact with people of same group.\n\nGroup 30-34 makes higher contacts with infants ( not too high suggesting a portion has no children ) , people from their age group and people of age 50-54, which makes sense, them being young parents.\n\nSimilarly, people of age 40 - 44 make contact with 5-9 and older children.\n\nGraph below is just a graphical representation of what was displayed above as rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np9 <- data.frame(\n  age_group     = dnames,\n  total_contacts = rowSums(mm)\n) |>\n  mutate(age_group = factor(age_group, levels = dnames)) |>\n  ggplot(aes(x = age_group, y = total_contacts)) +\n  geom_col(fill = \"#4393c3\", alpha = 0.85) +\n  labs(title = \"Total Daily Contacts by Age Group\",\n       x = \"Age group\", y = \"Avg daily contacts\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n\nprint(p9)\n```\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n",
    "supporting": [
      "intro_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}